theme = 'blowfish'
baseURL = "https://jcosta.dev/"
languageCode = "en"
pagination.pagerSize = 10

[imaging]
  anchor = 'Center'

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
