defaultAppearance = "dark"
enableSearch = true
enableCodeCopy = true

disableImageOptimization = true

defaultBackgroundImage = "img/westerlund2.jpg"

highlightCurrentMenuArea = true

fediCreator = "@julianocosta89@mastodon.social"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/westerlund2.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/posts"
  mainSections = ["posts", "talks"]
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = true
  sharingLinks = [ 
    "linkedin",
    "mastodon",
    "bluesky",
    "twitter",
    "reddit",
    "facebook",
    "email",
    "whatsapp",
    "telegram"
  ]

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
